//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPSyncdll
{
    using System;
    using System.Collections.Generic;
    
    public partial class BugHTML
    {
        public int ProjectID { get; set; }
        public int BugID { get; set; }
        public int FieldTypeID { get; set; }
        public int FieldID { get; set; }
        public string HTMLTextUcd { get; set; }
        public string HTMLText { get; set; }
    }
}
