//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPSyncdll
{
    using System;
    using System.Collections.Generic;
    
    public partial class BugTypes
    {
        public int ProjectID { get; set; }
        public int BugTypeID { get; set; }
        public string BugTypeName { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> OrderNo { get; set; }
    }
}
