//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPSyncdll
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerFieldTrackExt
    {
        public int ProjectID { get; set; }
        public int BugID { get; set; }
        public int SequenceNo { get; set; }
        public string Custom_1 { get; set; }
        public string Custom_2 { get; set; }
        public string Custom_3 { get; set; }
        public string Custom_4 { get; set; }
        public string Custom_5 { get; set; }
        public string Custom_6 { get; set; }
        public string Custom_7 { get; set; }
        public string Custom_8 { get; set; }
        public string Desc_Custom_1 { get; set; }
        public string Desc_Custom_2 { get; set; }
        public string Desc_Custom_3 { get; set; }
        public string Status_Custom_1 { get; set; }
        public string Status_Custom_2 { get; set; }
        public string Custom_201 { get; set; }
        public string Custom_202 { get; set; }
        public string Custom_203 { get; set; }
        public string Custom_204 { get; set; }
        public string Custom_205 { get; set; }
        public string Custom_206 { get; set; }
        public string Custom_207 { get; set; }
        public string Custom_208 { get; set; }
        public string Custom_301 { get; set; }
        public string Custom_302 { get; set; }
        public string Custom_303 { get; set; }
        public string Custom_304 { get; set; }
        public string Custom_305 { get; set; }
        public string Custom_306 { get; set; }
        public string Custom_307 { get; set; }
        public string Custom_308 { get; set; }
        public Nullable<double> Desc_Custom_1_Double { get; set; }
        public Nullable<int> Desc_Custom_1_Int { get; set; }
        public Nullable<System.DateTime> Desc_Custom_1_Date { get; set; }
        public Nullable<double> Desc_Custom_2_Double { get; set; }
        public Nullable<int> Desc_Custom_2_Int { get; set; }
        public Nullable<System.DateTime> Desc_Custom_2_Date { get; set; }
        public Nullable<double> Desc_Custom_3_Double { get; set; }
        public Nullable<int> Desc_Custom_3_Int { get; set; }
        public Nullable<System.DateTime> Desc_Custom_3_Date { get; set; }
        public string Custom_9Ucd { get; set; }
        public string Custom_10Ucd { get; set; }
        public string Custom_11Ucd { get; set; }
        public string Custom_12Ucd { get; set; }
        public string Custom_209Ucd { get; set; }
        public string Custom_210Ucd { get; set; }
        public string Custom_211Ucd { get; set; }
        public string Custom_212Ucd { get; set; }
        public string Custom_309Ucd { get; set; }
        public string Custom_310Ucd { get; set; }
        public string Custom_311Ucd { get; set; }
        public string Custom_312Ucd { get; set; }
        public string Custom_9 { get; set; }
        public string Custom_10 { get; set; }
        public string Custom_11 { get; set; }
        public string Custom_12 { get; set; }
        public string Custom_209 { get; set; }
        public string Custom_210 { get; set; }
        public string Custom_211 { get; set; }
        public string Custom_212 { get; set; }
        public string Custom_309 { get; set; }
        public string Custom_310 { get; set; }
        public string Custom_311 { get; set; }
        public string Custom_312 { get; set; }
    }
}
