//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPSyncdll
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerFieldTrackExt2
    {
        public int ProjectID { get; set; }
        public int IssueID { get; set; }
        public int PageNumber { get; set; }
        public string Custom_1 { get; set; }
        public string Custom_2 { get; set; }
        public string Custom_3 { get; set; }
        public string Custom_4 { get; set; }
        public string Custom_5 { get; set; }
        public string Custom_6 { get; set; }
        public string Custom_7 { get; set; }
        public string Custom_8 { get; set; }
        public string Custom_9Ucd { get; set; }
        public string Custom_10Ucd { get; set; }
        public string Custom_11Ucd { get; set; }
        public string Custom_12Ucd { get; set; }
        public string Custom_9 { get; set; }
        public string Custom_10 { get; set; }
        public string Custom_11 { get; set; }
        public string Custom_12 { get; set; }
    }
}
