//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPSyncdll
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueTimeTracking
    {
        public int ProjectID { get; set; }
        public int TimeItemID { get; set; }
        public int IssueID { get; set; }
        public int TimeItemOwnerID { get; set; }
        public int WorkTypeID { get; set; }
        public Nullable<double> TimeHours { get; set; }
        public Nullable<double> TimeHourlyRate { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> TimeItemFromDate { get; set; }
        public Nullable<System.DateTime> TimeItemToDate { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public string WorkTitle { get; set; }
        public Nullable<int> IfReady4Billing { get; set; }
        public Nullable<int> IfUsePlanRate { get; set; }
        public Nullable<int> LinkedEventID { get; set; }
        public Nullable<int> WorkTemplateID { get; set; }
        public Nullable<double> SalesTimeHourlyRate { get; set; }
        public Nullable<double> SalesTimeHours { get; set; }
        public Nullable<double> SalesTotalCost { get; set; }
        public Nullable<int> SalesMethod { get; set; }
        public Nullable<int> CostMethod { get; set; }
        public Nullable<int> IfClosed { get; set; }
        public Nullable<int> IfBillCustomer { get; set; }
        public Nullable<int> IfInvoiceSent { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> StandardUnitID { get; set; }
        public Nullable<int> CreatedByPersonID { get; set; }
        public Nullable<int> TimeTrackMethod { get; set; }
        public Nullable<int> HoursWorked { get; set; }
        public Nullable<int> TimeWorkedInHours { get; set; }
        public Nullable<int> TimeWorkedInMinutes { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<int> LinkedAssetID { get; set; }
        public Nullable<int> WorkCodeID { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public Nullable<int> DiscountLevelID { get; set; }
        public string WorkDescription { get; set; }
        public Nullable<int> TimeRemainInHours { get; set; }
        public Nullable<int> IfTimeRemain { get; set; }
        public Nullable<int> LinkedSvcAssetID { get; set; }
        public Nullable<int> LinkedSvcLineItemID { get; set; }
        public Nullable<double> TimeWorked { get; set; }
    }
}
