//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPSyncdll
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ABZG_DSEntities : DbContext
    {
        public ABZG_DSEntities()
            : base("name=ABZG_DSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bug> Bug { get; set; }
        public virtual DbSet<BugHTML> BugHTML { get; set; }
        public virtual DbSet<BugSelectionInfo> BugSelectionInfo { get; set; }
        public virtual DbSet<BugSelectionInfoText> BugSelectionInfoText { get; set; }
        public virtual DbSet<BugTypes> BugTypes { get; set; }
        public virtual DbSet<CustomerFieldListValue> CustomerFieldListValue { get; set; }
        public virtual DbSet<CustomerFieldTrackExt> CustomerFieldTrackExt { get; set; }
        public virtual DbSet<CustomerFieldTrackExt2> CustomerFieldTrackExt2 { get; set; }
        public virtual DbSet<IssueTimeTracking> IssueTimeTracking { get; set; }
        public virtual DbSet<LogIn> LogIn { get; set; }
        public virtual DbSet<PriorityTypes> PriorityTypes { get; set; }
        public virtual DbSet<SpaceLink> SpaceLink { get; set; }
        public virtual DbSet<SubProject> SubProject { get; set; }
        public virtual DbSet<SubProjectTree> SubProjectTree { get; set; }
        public virtual DbSet<ProgressStatusTypes> ProgressStatusTypes { get; set; }
        public virtual DbSet<SubProjectOwners> SubProjectOwners { get; set; }
        public virtual DbSet<TimeSheet> TimeSheet { get; set; }
        public virtual DbSet<TimeSheetEntry> TimeSheetEntry { get; set; }
        public virtual DbSet<TimeSheetHour> TimeSheetHour { get; set; }
    }
}
