//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPSyncdll
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpaceLink
    {
        public int ProjectID { get; set; }
        public Nullable<int> ProjectTypeID { get; set; }
        public int SpaceID { get; set; }
        public int ToProjectID { get; set; }
        public Nullable<int> ToProjectTypeID { get; set; }
        public int ToSpaceID { get; set; }
        public Nullable<int> IsPrimary { get; set; }
    }
}
