//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPSyncdll
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubProject
    {
        public int ProjectID { get; set; }
        public int SubProjectID { get; set; }
        public string SubProjectCode { get; set; }
        public string Title { get; set; }
        public Nullable<int> CreatedByPerson { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CurrentOwner { get; set; }
        public Nullable<int> ProgressStatusID { get; set; }
        public Nullable<int> AssignedByPersonID { get; set; }
        public Nullable<System.DateTime> DateAssigned { get; set; }
        public Nullable<int> ClosedByPerson { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public Nullable<int> ProjectPriorityID { get; set; }
        public Nullable<int> PercentComplete { get; set; }
        public string CustomField1 { get; set; }
        public string CustomField2 { get; set; }
        public string CustomField3 { get; set; }
        public string CustomField4 { get; set; }
        public Nullable<short> IfClosed { get; set; }
        public Nullable<int> EstimatedHours { get; set; }
        public Nullable<double> EstimatedCost { get; set; }
        public Nullable<int> ActualHours { get; set; }
        public Nullable<double> ActualCost { get; set; }
        public Nullable<System.DateTime> PlanedStartDate { get; set; }
        public Nullable<System.DateTime> PlanedEndDate { get; set; }
        public Nullable<System.DateTime> DeadlineDate { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public Nullable<int> DocumentFolderID { get; set; }
        public Nullable<int> LastUpdateNo { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> EmailStatusBits { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> ServicePlanID { get; set; }
        public Nullable<int> DefaultIncidentTemplateID { get; set; }
        public Nullable<int> PrimaryManager { get; set; }
        public Nullable<int> SecondaryManager { get; set; }
        public Nullable<int> IfMarketingCampaign { get; set; }
        public Nullable<double> ExpectedSales { get; set; }
        public Nullable<double> ActualSales { get; set; }
        public Nullable<int> SubProjectType { get; set; }
        public Nullable<int> SubProjectCategoryID { get; set; }
        public Nullable<int> SubProjectIssueStatusOption { get; set; }
        public Nullable<int> SubProjectEventOption { get; set; }
        public Nullable<int> TeamMemberOption { get; set; }
        public Nullable<int> CustomerOption { get; set; }
        public Nullable<int> TeamMemberAccessOption { get; set; }
        public Nullable<int> CustomFieldInt1 { get; set; }
        public Nullable<int> CustomFieldInt2 { get; set; }
        public Nullable<int> CustomFieldInt3 { get; set; }
        public Nullable<int> CustomFieldInt4 { get; set; }
        public Nullable<int> SamePropertyAsParent { get; set; }
        public Nullable<int> DefaultCustomerID { get; set; }
        public Nullable<int> DueDateInheritanceOption { get; set; }
        public Nullable<int> DueDateEnforcedByParentID { get; set; }
        public Nullable<int> DeliverDateInheritanceOption { get; set; }
        public Nullable<int> DeliverDateEnforcedByParentID { get; set; }
        public Nullable<int> ReleaseInheritanceOption { get; set; }
        public Nullable<int> ReleaseEnforcedByParentID { get; set; }
        public Nullable<int> NotesInheritanceOption { get; set; }
        public Nullable<int> NotesEnforcedByParentID { get; set; }
        public Nullable<int> WorkflowID { get; set; }
        public Nullable<int> WorkflowInheritanceOption { get; set; }
        public Nullable<int> WorkflowEnforcedByParentID { get; set; }
        public Nullable<int> IsMileStone { get; set; }
        public Nullable<int> TMAccessInheritanceOption { get; set; }
        public Nullable<int> TMAccessEnforcedByParentID { get; set; }
        public Nullable<int> TeamMemberInheritanceOption { get; set; }
        public Nullable<int> TeamMemberEnforcedByParentID { get; set; }
        public Nullable<int> ReleaseFolderTypeID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> VersionID { get; set; }
        public Nullable<int> BuildID { get; set; }
        public Nullable<int> IssueTypeID { get; set; }
        public Nullable<int> CrntLogItemID { get; set; }
        public Nullable<int> LinkedSpecID { get; set; }
        public Nullable<int> LinkedTypeID { get; set; }
        public Nullable<int> IterationNumber { get; set; }
        public Nullable<int> IssueTemplateID { get; set; }
        public string CloseDescription { get; set; }
        public string ProjectDescription { get; set; }
        public Nullable<int> EstimatedTimeTotal { get; set; }
        public Nullable<int> SpecificationPoint { get; set; }
        public Nullable<int> LinkedImplementationCopyID { get; set; }
        public Nullable<int> LinkedStoryItemID { get; set; }
        public Nullable<int> ProductVersionOption { get; set; }
        public Nullable<int> ProductVerInheritOption { get; set; }
        public Nullable<int> SupportReleaseBacklog { get; set; }
        public Nullable<int> DevelopmentMethod { get; set; }
        public Nullable<int> TeamSupportOption { get; set; }
        public Nullable<int> SupportSubReleaseOption { get; set; }
        public Nullable<int> DefaultRequirementSpace { get; set; }
        public Nullable<int> DefaultSpecSubmitFolder { get; set; }
        public Nullable<int> MyDevSuiteAccessOption { get; set; }
        public Nullable<int> DefaultTemplateSpace { get; set; }
        public Nullable<int> DefaultTemplateSubmitFolder { get; set; }
        public Nullable<int> ReleaseID { get; set; }
        public Nullable<int> SyncOptionForPPMTitle { get; set; }
        public Nullable<int> SyncOptionForPPMReleaseInfo { get; set; }
        public Nullable<int> DefaultTaskSubmitFolder { get; set; }
        public Nullable<int> ProjectSpaceTypeID { get; set; }
        public Nullable<int> SubPlanOption { get; set; }
        public Nullable<int> SubPlanStatusID { get; set; }
        public Nullable<int> MilestoneID { get; set; }
        public Nullable<int> DelayDegree { get; set; }
        public Nullable<int> DelayDays { get; set; }
        public string DelayReason { get; set; }
        public Nullable<int> SupportWIPLimits { get; set; }
        public string ProgressDescription { get; set; }
        public Nullable<int> ParentProjectSpace { get; set; }
    }
}
