//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPSyncdll
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheetHour
    {
        public int TSProjectID { get; set; }
        public int TimeSheetID { get; set; }
        public int TimeEntryID { get; set; }
        public int SequenceID { get; set; }
        public Nullable<System.DateTime> TimeEntryDate { get; set; }
        public Nullable<double> TimeEntryHours { get; set; }
    }
}
